### ISSUE TITLE
Error finding curses on windows

### ISSUE THREAD

**Issue by AndersPanders123** [evanlaube/termify#2]
Hi, i might be doing it wrong but when i try running the application after downloading al the necessary installations i just get an error saying: "File "<frozen runpy>", line 198, in _run_module_as_main", and a few other things. It also says there is no module named "_curses". This is the whole error after writing "temify" in the console.
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\anders.hoelstad\AppData\Local\Programs\Python\Python312\Scripts\termify.exe\__main__.py", line 4, in <module>
  File "C:\Users\anders.hoelstad\AppData\Local\Programs\Python\Python312\Lib\site-packages\termify\__main__.py", line 3, in <module>
    from termify.spotifyAppController import SpotifyAppController
  File "C:\Users\anders.hoelstad\AppData\Local\Programs\Python\Python312\Lib\site-packages\termify\spotifyAppController.py", line 2, in <module>
    import curses
  File "C:\Users\anders.hoelstad\AppData\Local\Programs\Python\Python312\Lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```
Please tell me if i am doing it wrong of if it is a mistake in the code.

**Comment by evanlaube** [comment]
It looks like you're running windows correct? So far tests have only been run on MacOS and Linux. I can try and test it in my windows machine later, but it looks like the issue is something to do with Curses. Make sure that it is installed on your machine

**Comment by evanlaube** [comment]
Looks like the issue is that you don't have `windows-curses` installed on your machine. I've added it to the build dependencies in `setup.py`, but if it still doesn't install on your machine you can fix your issue by manually running `pip install windows-curses`

**Comment by AndersPanders123** [comment]
Nice, it works now.
Thank you :)

**Comment by evanlaube** [comment]
Glad it works for you!
